"""
Clean stale scenario files before a fresh campaign generation.
Digital immune system — utils/clean_scenarios.py

The attack/adaptive generators write NEW timestamped files each run and never delete
the old ones, so re-running a campaign accumulates stale scenarios and `red_team all`
would execute base + adaptive + leftovers together (reviewer: campaign isolation).
This removes:
  * ALL adaptive scenarios (scenarios/*/adaptive/*.json) — fully regenerated by adapt;
  * GENERATED base scenarios whose id is a timestamp (ATK-<8digits>-<6digits>.json);
KEEPING hand-written base scenarios whose id is NOT a pure timestamp (e.g.
ATK-BFULL-VOTECHANGE.json), which no generator recreates.

Usage:
  python utils/clean_scenarios.py            # dry-run (shows what would be removed)
  python utils/clean_scenarios.py --yes      # actually delete
"""

import os
import re
import sys
import glob
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from env_loader import load_config

_cfg = load_config()
ROOT = Path(_cfg.get("_root", Path(__file__).resolve().parent.parent))
SCEN = ROOT / _cfg.get("paths", {}).get("scenarios_dir", "scenarios")

# a purely generated id: ATK-<8 digits>-<6 digits>  (e.g. ATK-20260607-080734)
_GENERATED_ID = re.compile(r"^ATK-\d{8}-\d{6}(_adaptive)?\.json$")


def collect() -> tuple:
    """Return (adaptive_files, generated_base_files, kept_base_files)."""
    adaptive, generated, kept = [], [], []
    for f in glob.glob(str(SCEN / "**" / "*.json"), recursive=True):
        p = Path(f)
        if "report" in p.name:
            continue
        if "adaptive" in p.parts:
            adaptive.append(f)
        elif _GENERATED_ID.match(p.name):
            generated.append(f)
        else:
            kept.append(f)            # hand-written base (e.g. B-full) — preserved
    return sorted(adaptive), sorted(generated), sorted(kept)


def main():
    do_it = "--yes" in sys.argv
    adaptive, generated, kept = collect()
    to_remove = adaptive + generated
    print("=" * 66)
    print("  🧹 ОЧИСТКА STALE-СЦЕНАРІЇВ" + ("" if do_it else "  (dry-run — додай --yes)"))
    print("=" * 66)
    print(f"  Адаптивних до видалення:        {len(adaptive)}")
    print(f"  Згенерованих базових до видалення: {len(generated)}")
    print(f"  Ручних базових ЗБЕРЕЖЕНО:        {len(kept)}")
    for f in kept:
        print(f"     ↳ keep: {Path(f).name}")
    if do_it:
        for f in to_remove:
            try:
                os.remove(f)
            except OSError:
                pass
        print(f"\n  ✅ Видалено {len(to_remove)} файлів. Базовий каталог тепер лише "
              f"ручні сценарії — регенеруй генератором.")
    else:
        print(f"\n  Буде видалено {len(to_remove)} файлів. Запусти з --yes.")
    print("=" * 66)


if __name__ == "__main__":
    main()
